### ISSUE TITLE
systemd support with mounts

### ISSUE THREAD

**Issue by samip5** [desultory/ugrd#60]
I'm kryptonian on #gentoo IRC.

It would be awesome if it worked properly with disk mounting, as currently it requires me to do mount -a in an emergency shell to get into my system.

**Comment by desultory** [comment]
I'm glad it mostly worked for you. The systemd mounting issue is because ugrd doesn't use udev, so systemd doesn't see that mounts are available. In the latest version on git, you should be able to use the `ugrd.fs.fakeudev` module to trick systemd into thinking the mounts are available. this module can be added to the modules defined in `/etc/ugrd/config.toml`

**Comment by desultory** [comment]
that particular symlink (hardlink) should be created by cryptsetup when it `open`s the device. I think it failing there is totally fine, because it's already done.
