### ISSUE TITLE
Is it possible to decrypt full disk?

### ISSUE THREAD

**Issue by evdenis** [desultory/ugrd#7]
Let's suppose there is a fully encrypted drive without partitions. I can only find uuid and partuuid options for cryptsetup. However, there is no uuid of /dev/sda, for example. Is it possible to specify it somehow?

**Comment by desultory** [comment]
If you have a drive that has just encrypted data (detached LUKS headers) you can tell UGRD the `partuuid` of the partition, and specify header/key files to use to decrypt that.

I'm currently using a similar setup on my laptop.

By design, UGRD does not want to let you embed keys into the image, and prefers you have keys/headers/sensitive data on another device that is mounted at runtime. There is nothing stopping you from copying key files into the image, there just aren't config macros made for it.

In most situations it makes more sense to keep your headers attached, since there is risk associated with people copying your headers if they are on some other device. If the headers are on disk, that is a tiny bit of metadata that is left behind, but it can make that data a bit more difficult to steal. If you kept those keys on a USB drive, someone could theoretically copy those rather quickly. Depending on your system security, it can be rather involved to read the LUKS headers, especially from a live system where an attacker doesn't have root access. They would likely need to reboot the system or remove the hard drive to extract that info.

**Comment by evdenis** [comment]
Thank you for the clarification!

**Comment by desultory** [comment]
> Thank you for the clarification!

I missed one detail, `uuid` generally refers to a "filesystem uuid" where `partuiid` refers to a partition.

I'm not sure if you can just use a plain raw disk without some extra steps. I think it should be possible, but it's generally best to just use some sort of partition scheme, it makes it easier for your computer to know where data is.

Some more related info is here: https://discussion.fedoraproject.org/t/how-to-install-fedora-25-in-lvm-on-luks-without-a-partition-table/76526/8

I encourage you to use UGRD as a base for something, you can have it pull the deps you need, and make a basic init file, and then you can edit that to do exactly what you need. This was the original design purpose. It shouldn't be too hard to write your own modules/edit existing ones either, if you know Python.
