### ISSUE TITLE
RuntimeError: 'btrfs' not found in PATH

### ISSUE THREAD

**Issue by P-reducible** [desultory/ugrd#77]
I am doing a fresh Gentoo install as explained [here](https://wiki.gentoo.org/wiki/Full_Disk_Encryption_From_Scratch). My EFI partition is at `/dev/nvme0n1p1`, my `ext4` `/boot` partition is at `/dev/nvme0n1p2`, and `/dev/nvme0n1p3` is a _password-protected_ LUKS volume containing `/dev/mapper/root` with a single subvolume named `/home`. After the kernel (`gentoo-sources-6.10.12`) has been built, executing `ugrd-1.22.0` with no parameters causes [this](https://paste.gentoo.zip/5F7TB7zp) error. Is this a bug, or I genuinely missed something?

Many thanks.

**Comment by P-reducible** [comment]
@desultory, thank you for replying. The `/etc/mtab` shows

> /dev/mapper/root / btrfs rw,realtime,ssd,space_cache=v2,subvolid=5,subvol=/ 0 0

As you suggested, I installed `btrfs-progs`, and it fixed the problem. My new log is [here](https://paste.gentoo.zip/XKjOZPuv).

One suggestion, if I may. Your code checks if `btrfs` is present, and if so, executes it. There is an opinion that doing it this way creates a security risk. (Not to mention an obvious race condition). Would it make sense to just run `btrfs` straight away? Same argument as when you want to open a file: you just go for it without worrying if the file exists.

Thx again.

**Comment by desultory** [comment]
> @desultory, thank you for replying. The `/etc/mtab` shows
> 
> > /dev/mapper/root / btrfs rw,realtime,ssd,space_cache=v2,subvolid=5,subvol=/ 0 0
> 
> As you suggested, I installed `btrfs-progs`, and it fixed the problem. My new log is [here](https://paste.gentoo.zip/XKjOZPuv).
> 
> One suggestion, if I may. Your code checks if `btrfs` is present, and if so, executes it. There is an opinion that doing it this way creates a security risk. (Not to mention an obvious race condition). Would it make sense to just run `btrfs` straight away? Same argument as when you want to open a file: you just go for it without worrying if the file exists.
> 
> Thx again.

I don't think the build system runs it. The error you saw came from it trying to copy the `btrfs` program from the root filesystem into the build environment, and since it was not present, it raised an exception. The `btrfs` program is listed as a dependency in the `ugrd.fs.btrfs` module, which can be loaded manually, but is automatically loaded at run time if a mount with the btrfs type is added.

There is an `opt_dependencies` type of dependency in ugrd which allows for an image to be created if the requested binary cannot be found, but in this case something is wrong if btrfs is being used but btrfs utilities aren't present.

**Comment by desultory** [comment]
Please let me know if you still see a problem with the current design, I think this portion is safe, and should not execute anything needlessly.
