### ISSUE TITLE
Cannot use detached header on a device that has no UUID or PARTUUID

### ISSUE THREAD

**Issue by akiraowen** [desultory/ugrd#8]
I have a device that was encrypted directly (no partition information) with the detached headers option:
```
#cryptsetup luksFormat --header luks_header.img /dev/sda
```
Doing this means that the device /dev/sda has no UUID or no PARTUUID and looking at the code, ugrd doesn't support this use case.

ugrd can be successfully used on this partition in the case where the header is in place because it then has a UUID and everything else works (password, keyfile, gpg+keyfile, etc).

**Comment by akiraowen** [comment]
My current work around is to comment out cryptsetup.py lines:
```
59    #if config.get('header_file') and not config.get('partuuid'):
60    #    raise ValueError("A partuuid must be specified when using detached headers: %s" % mapped_name)
61    #elif not config.get('partuuid') and not config.get('uuid'):
62    #    raise ValueError("Either a uuid or partuuid must be specified with cryptsetup mounts: %s" % mapped_name)
...
100        source_cmd = f'export CRYPTSETUP_SOURCE_{name}=/dev/sda'#$(blkid --match-token "$SOURCE_TOKEN_{name}" --match-tag PARTUUID --output device)'
```

**Comment by desultory** [comment]
Is there a particular reason why you're not using any partition table? I specifically designed UGRD to use UUIDs so it should be reliable, as device paths can change. If you think there is a good reason to allow using raw device paths, UGRD can be modified to allow that, but I find using device paths like this is generally unreliable.

You're not the first person who has tried to do something like this. 

The main concern is that UGRD attempts to verify config information, and you could verify device paths, but it's a bit pointless to verify them because the order could change on reboot. Allowing device paths over UUIDs can break verification, so at the very least, this usage should probably only be allowed if validation is disabled as well.

**Comment by desultory** [comment]
I've pushed changes to allow path usage with detached headers only when validation is disabled.

I haven't made a release for this yet, would you mind pulling the latest changes in the repo to see if that works for you?

**Comment by akiraowen** [comment]
The idea is that a "fully encrypted" device would mean that there is no partition information or even an empty area with and offset size that would indicate a LUKS header once lived there (the drive will not give up any clue). In my case a USB is used to boot the system and is removed afterwards, the main encrypted drive is never removed and is set consistently in the BIOS default settings. I find NVME/SATA devices are always the same unless you mess with BIOS order. USB devices will shuffle around depending on who gets detected first. Yeah I prefer UUID's anyway 😅

I've tested your change and it works! Thanks!

**Comment by desultory** [comment]
That makes sense, I do something similar, but target something like "full system encryption". By that, I mean someone will see I have a drive with one big partition, and that's it. While this reveals something, it makes booting more reliable, and config more manageable.

I'll probably keep this as a sort of hidden feature, for advanced users.
